services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ingress/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./ingress/caddy-data:/data
      - ./ingress/caddy-config:/config

